### ISSUE TITLE
For chapter card create modal window with intro of book and intro of chapter

### ISSUE THREAD

**Issue by foxprogs** [texttree/bsa#219]

**Comment by Valyukhov** [comment]
@foxprogs  What for? what event will be open this dialog? What kind of intro do you want. Share us please.

**Comment by foxprogs** [comment]
@Valyukhov  As you know, in the TN resource we have a chapter "front" and in each chapter there is a verse "intro". I think maybe we will add the first line to the Chapter component - this is "Chapter X" and 2 buttons: "Book Introduction" and "Chapter Introduction". When pressed, we can open a modal window with these TN articles.

**Comment by Valyukhov** [comment]
i think i can try this

**Comment by Valyukhov** [comment]
@foxprogs maybe like this
![изображение.png](https://images.zenhubusercontent.com/615d3ffc38622d394ceed039/b02644b1-4748-441b-8400-b3106a3dd693)
