### ISSUE TITLE
In OBS we can close last obs 

### ISSUE THREAD

**Issue by Valyukhov** [texttree/bsa#235]
Maybe it can be  after added new subjects resources

**Comment by foxprogs** [comment]
![изображение](https://user-images.githubusercontent.com/30548361/139601442-aa4f5c20-1bd4-43d6-abcb-e0ab6468849a.png)
проблема потому что у нас тут два ресурса, а условие такое, что если один ресурс остался - тогда не закрывать. Так что баг пропадет когда в исключения добавим книгу
