### ISSUE TITLE
Make tAcademy reference in tNote to be a live link

### ISSUE THREAD

**Issue by russp41** [texttree/bsa#318]
Make tAcademy reference be a live link to the referenced article in the language of the resources being viewed.

![image](https://user-images.githubusercontent.com/10854620/156224139-de81c7fd-b108-4c7f-8479-229bdeff8eda.png)

**Comment by foxprogs** [comment]
@russp41
Abel from the Spanish team added tA support.
You can add an Academy card and a Notes card. When a note opens, it automatically loads the desired article from the Academy.

By the end of the week we plan to make this release(1.6.0). Also there will be the ability to save the position of the cards(layout), there will be support for more resources.

Thanks for the feedback, sorry we didn't reply sooner.

**Comment by Valyukhov** [comment]
@russp41 we fixed it in  1.8.0
