### ISSUE TITLE
Improve the lexicon to show the gloss

### ISSUE THREAD

**Issue by birchamp** [texttree/bsa#364]
In OBT the hover over for the lexicon doesn't show the gloss
![CleanShot 2022-04-21 at 10 00 51](https://user-images.githubusercontent.com/10272744/164474821-2c74175b-7d95-4b33-b9f1-fe9d1407709c.png)

But a better lexicon would show the gloss like https://github.com/unfoldingWord-box3/translation-helps
![CleanShot 2022-04-21 at 10 00 33](https://user-images.githubusercontent.com/10272744/164475393-4f1cb2e3-08e2-42f9-9ec8-5ee91e6acf71.png)

**Comment by Valyukhov** [comment]
https://github.com/unfoldingWord-box3/translation-helps/blob/7d255189997d369d6b0a981833f6c24aafa5bd70/src/components/Viewer/Workspace/Scripture/ScriptureView/VerseObject/AlignedWords/AlignedWord/helpers.js

**Comment by Valyukhov** [comment]
https://git.door43.org/unfoldingWord/en_ugl
